### ISSUE TITLE
Error: Async fragment (lasso-slot:head) timed out after 30000ms

### ISSUE THREAD

**Issue by giovannipds** [lasso-js/lasso-marko-taglib#37]
I constantly face this error in the view item team working in `viewitem_nodestar`, which stops occurring if I put a high value at [slot-tag.js line 55](https://github.com/lasso-js/lasso-marko-taglib/blob/master/taglib/slot-tag.js#L55).

We're using `"@lasso/marko-taglib": "^1.0.15"` and `"node": ">=18.13.0"`.

<img width="992" alt="Screenshot 2023-08-11 at 17 27 32" src="https://github.com/lasso-js/lasso-marko-taglib/assets/1820017/2fb22325-728a-45e2-bd8f-f2e1976da774">

Anyone has any idea on how to avoid it or fix it permanently? If it's a library issue, could be good releasing a fix. Thanks

Cc @DylanPiercey

**Comment by DylanPiercey** [comment]
This is not an issue with this module, you can configure the timeout via the `<lasso-page>` tags timeout option (https://github.com/lasso-js/lasso-marko-taglib/tree/master#lasso-page).

The purpose of this timeout is to avoid issues where if for some reason the bundling, asset, upload, or something else causes lasso to never complete that it doesn't create a memory leak and/or leave the request hanging for too long.

The timeout itself is not the issue, the issue is whatever is making it take that long to bundle, assuming things are working, or whatever caused the bundle to never finish.

You can also cause the timeout to be disabled entirely by setting the `timeout` option in the `<lasso-page>` tag to `0`.
